services:
  app:
    build: .
    container_name: drf-api
    ports:
      - "8000:8000"
    env_file:
      - .env.development
    volumes:
      - .:/usr/local/app/
    tty: true
    stdin_open: true
    command: python parse_wb/manage.py runserver 0.0.0.0:8000
  celery:
    build: .
    container_name: celery-worker
    env_file:
      - .env.development
    volumes:
      - .:/usr/local/app/
    tty: true
    entrypoint: /usr/local/app/celery_entrypoint.sh
  postgres:
    image: postgres:16
    container_name: postgres_test_db
    env_file:
      - .env.development
    volumes:
        - postgresql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: postgre_db_viewer_pgadmin
    depends_on:
      - postgres
    ports:
      - "5052:80"
    env_file:
      - .env.development
  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
    postgresql-data:
    redis-data: