[tool.black]
line-length=79

[tool.mypy]
warn_unused_configs = true
pretty = true
strict = true
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]

[tool.django-stubs]
django_settings_module = "parse_wb.parse_wb.settings"
