# Generated by Django 5.1.2 on 2024-10-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CardData",
            fields=[
                (
                    "article",
                    models.CharField(primary_key=True, serialize=False),
                ),
                ("card_data", models.JSONField()),
                ("price_history_data", models.JSONField()),
                ("info_data", models.JSONField()),
            ],
        ),
    ]
